const experience = {
  title: "Experience",
  icon: null,
  description: null,
  list: [
    {
      title: "Team Lead",
      subtitle: "Collinson Group - via Arnia",
      subtitleLink: "https://www.collinsongroup.com/",
      tags: [
        "glue",
        "kafka",
        "redis",
        "hadoop",
        "step functions",
        "kubernetes",
        "s3",
        "reactjs",
      ],
      description: [
        "Led planning, design, architecture & implementation for team of 4 in creating serverless redemption platform with B2B & B2C API's on Lambda alongside whitelabel ReactJS web",
        "Successfully liased with multiple up/down stream systems in integrating new proxy wrapper enriching payload for customers via Kafka streaming jobs to workers & retrieving from Redis",
        "Designed and implemented generic plugin based gateway used across departments to integrate with multiple downstream vendors & enrichen via ETL PySpark jobs on Hadoop",
      ],
    },
    {
      title: "Senior Software Engineer",
      subtitle: "Well Pharmacy - via Arnia",
      subtitleLink: "https://www.well.co.uk/",
      tags: [
        "go",
        "lambda",
        "dynamodb",
        "hadoop",
        "step functions",
        "s3",
        "reactjs",
        "cognito",
      ],
      description: [
        "Created passwordless magic link sign in/up system used across all of the companies sites",
        "Setup event-driven ETL pipeline over 10`s of TB of S3 customer data lake in parallelized PySpark worker environment Hadoop to extract BI used across products",
        "Cut down load on pharmacists by 27% via ReactJS website and Go backend on Lambda providing self-service portal for customers",
      ],
    },
    {
      title: "Senior Software Engineer",
      subtitle: "E.ON - via Arnia",
      subtitleLink: "https://www.eon.com/",
      date: "March 2020 - February 2021",
      tags: ["kubernetes", "Azure", "Functions", "Cosmos", "NodeJS", "AKS"],
      description: [
        "Setup monitoring of components via ELK stack on AKS that greatly reduced MTTR",
      ],
    },
    {
      title: "Senior Software Engineer",
      subtitle: "Collinson Group",
      subtitleLink: "https://www.collinsongroup.com/",
      date: "March 2018 - February 2020",
      tags: [
        "AWS",
        "Lambda",
        "ECS",
        "EC2",
        "RDS",
        "DynamoDB",
        "NodeJS",
        "Kotlin",
        "Terraform",
        "AKS",
        "Cosmos",
      ],
      description: [
        "Led team of 3 to create cluster based blockchain ledger platform. Developed on NodeJS, Kotlin & ReactJS running on ECS with self-checkout customer node expansion via Terraform",
        "Delivered serverless platform digitizing manual tasks of foundation with 50+ clients from brainstorming journeys, wireframes to coding. Platform was written in NodeJS & ReactJS on S3, Lambda, DynamoDB with CI/CD",
        "Managed & developed Workplace NLP bot as L1 support used by 250+ employees. Added ReactJS HR dashboard for human chat escalation, nominations & meeting room bookings",
      ],
    },
    {
      title: "Cloud Software Engineer",
      subtitle: "Cahootsy",
      date: "July 2017 - March 2018",
      tags: [
        "lambda",
        "ecs",
        "sqs",
        "s3",
        "nodejs",
        "elasticsearch",
        "etl",
        "nlp",
      ],
      description: [
        "Reduced by 90% existing 5 days serial error prone process via an event driven fault tolerant ETL. NLP datasets used to generate optimal targeted campaigns to reduce costs",
      ],
    },
    {
      title: "Software Developer",
      subtitle: "Citi",
      subtitleLink: "https://citi.com",
      subtitleDetail: " - Rates Pricing E-Trading Technology",
      date: "September 2016 - July 2017",
      tags: ["java", "spring", "low-latency", "docker", "nodejs", "kubernetes"],
      description: [
        "Consolidated streaming of realtime pricing data to 100's of downstream systems via a real-time low latency asynchronous graph based distributed aggregation system in Java Spring",
        "Reduced by 65% testing time of strategic logic by creating generic Cucumber test generator",
        "Set code quality standards via Kubernetes based ETL job on top of code build data in ELK",
      ],
    },
    {
      title: "Software Engineer",
      subtitle: "Citi",
      subtitleLink: "https://citi.com",
      subtitleDetail: " - Futures E-Trading Technology",
      date: "September 2015 - September 2016",
      tags: ["java", "spring", "low-latency", "angularjs", "nodejs"],
      description: [
        "Successfully did fundamental architectural change to major project by replacing duplicate JSP pages with modular Angular web and observer, decorator, adapter based Java backend",
        "Cut by 70% code duplication via a common shared library as measured in SonarQube",
      ],
    },
    {
      title: "Software Engineer",
      subtitle: "Nomura",
      subtitleLink: "http://nomura.com",
      subtitleDetail: " - Web Services Technologies",
      date: "June 2013 - June 2014",
      tags: ["java", "spring"],
      description: [
        "Reduced team load by 95% on majority of daily tasks via Python and Java automation",
      ],
    },
  ],
};

export default experience;
